### ISSUE TITLE
Add new project MovieChat

### ISSUE THREAD

**Issue by wenhaochai** [showlab/Awesome-Long-Context#1]
Thanks for collecting a awesome list for long video understanding. Our MovieChat is a framework that can handle >10k frames~
[website] https://rese1f.github.io/MovieChat
[code] https://github.com/rese1f/MovieChat
techique report is coming soon with a new dataset released.

**Comment by QinghongLin** [comment]
Sure, happy to include MovieChat, great work!

**Comment by wenhaochai** [comment]
thanks!
